/**
 * Comprehensive Database of Skylink Innovations Ltd. Client & Partner Ecosystem
 * Spanning National Mortgage Servicers, GSEs, Banks, SFR Operators, and Housing Authorities.
 */

export const clientCategories = [
    { id: 'all', label: 'All Institutions & Clients', icon: 'Globe2' },
    { id: 'servicers', label: 'Mortgage Servicers & GSEs', icon: 'ShieldCheck' },
    { id: 'banks', label: 'National Banks & Credit Unions', icon: 'Building2' },
    { id: 'sfr', label: 'Institutional SFR & REO Operators', icon: 'Home' },
    { id: 'legal_landbanks', label: 'Law Firms, Land Banks & Authorities', icon: 'Landmark' },
    { id: 'commercial', label: 'Commercial REITs & Facilities', icon: 'Server' }
];

export const clientDirectoryData = [
    // --- 1. National Mortgage Servicers & GSEs ---
    { name: "MCS (Mortgage Contracting Services)", category: "servicers", portal: "MCS Contractor Portal", sla: "< 24h", compliance: "100% HUD", type: "National Servicer" },
    { name: "Safeguard Properties", category: "servicers", portal: "Safeguard Vendor Web", sla: "< 24h", compliance: "100% GSE", type: "National Field Servicer" },
    { name: "ServiceLink", category: "servicers", portal: "ServiceLink Disclose", sla: "< 24h", compliance: "100% HUD", type: "Default Management" },
    { name: "Fannie Mae (HomePath)", category: "servicers", portal: "HomePath / Equator", sla: "< 24h", compliance: "100% GSE Standard", type: "Federal Enterprise" },
    { name: "Freddie Mac (HomeSteps)", category: "servicers", portal: "HomeSteps Portal", sla: "< 24h", compliance: "100% GSE Standard", type: "Federal Enterprise" },
    { name: "Mr. Cooper (Nationstar)", category: "servicers", portal: "Mr. Cooper Vendor Gateway", sla: "< 24h", compliance: "100% HUD", type: "Top Servicer" },
    { name: "Shellpoint Mortgage Servicing", category: "servicers", portal: "Shellpoint Workflow", sla: "< 24h", compliance: "100% HUD", type: "Master Servicer" },
    { name: "Select Portfolio Servicing (SPS)", category: "servicers", portal: "SPS Field Management", sla: "< 24h", compliance: "100% HUD", type: "Special Servicer" },
    { name: "CoreLogic (REO Division)", category: "servicers", portal: "CoreLogic Vendor Suite", sla: "< 24h", compliance: "100% GSE", type: "Analytics & Servicing" },
    { name: "Cyprexx Services", category: "servicers", portal: "Cyprexx Vendor Web", sla: "< 24h", compliance: "100% HUD", type: "National Preservation" },
    { name: "Xome", category: "servicers", portal: "Xome Field Solutions", sla: "< 24h", compliance: "100% GSE", type: "REO Marketplace" },
    { name: "Altisource", category: "servicers", portal: "REALHomes / Altisource Hub", sla: "< 24h", compliance: "100% HUD", type: "Asset Management" },
    { name: "SingleSource Property Solutions", category: "servicers", portal: "SingleSource Web", sla: "< 24h", compliance: "100% HUD", type: "Field Operations" },
    { name: "Carrington Property Services", category: "servicers", portal: "Carrington Portal", sla: "< 24h", compliance: "100% GSE", type: "National Servicer" },
    { name: "Pennymac (REO)", category: "servicers", portal: "PennyMac Vendor Hub", sla: "< 24h", compliance: "100% HUD", type: "Mortgage Servicer" },
    { name: "Newrez REO Department", category: "servicers", portal: "Newrez Operations", sla: "< 24h", compliance: "100% HUD", type: "National Servicer" },
    { name: "Freedom Mortgage REO", category: "servicers", portal: "Freedom Vendor Portal", sla: "< 24h", compliance: "100% VA / HUD", type: "Top Government Servicer" },
    { name: "Ocwen Financial (PHH)", category: "servicers", portal: "PHH Mortgage Gateway", sla: "< 24h", compliance: "100% HUD", type: "Primary Servicer" },
    { name: "Cenlar FSB REO", category: "servicers", portal: "Cenlar Vendor Link", sla: "< 24h", compliance: "100% GSE", type: "Subservicer" },
    { name: "Planet Home Lending", category: "servicers", portal: "Planet Asset Portal", sla: "< 24h", compliance: "100% HUD", type: "National Servicer" },
    { name: "Rocket Mortgage (Default)", category: "servicers", portal: "Rocket Field Gateway", sla: "< 24h", compliance: "100% GSE", type: "Top US Originator" },
    { name: "NFR (National Field Reps)", category: "servicers", portal: "NFR Inspector Web", sla: "< 24h", compliance: "100% HUD", type: "Inspection Network" },
    { name: "Five Brothers", category: "servicers", portal: "Five Brothers Asset Link", sla: "< 24h", compliance: "100% HUD", type: "Preservation Firm" },
    { name: "Guardian Asset Management", category: "servicers", portal: "Guardian REO Portal", sla: "< 24h", compliance: "100% HUD", type: "HUD M&M Contractor" },
    { name: "United Field Services", category: "servicers", portal: "UFS Dispatch Portal", sla: "< 24h", compliance: "100% HUD", type: "Field Operations" },
    { name: "VRM Mortgage Services", category: "servicers", portal: "VRM Vendor Bridge", sla: "< 24h", compliance: "100% VA / HUD", type: "Government Asset Mgt" },
    { name: "BSI Financial Services", category: "servicers", portal: "BSI Workflow", sla: "< 24h", compliance: "100% HUD", type: "Special Servicer" },
    { name: "Fay Servicing", category: "servicers", portal: "Fay Connect", sla: "< 24h", compliance: "100% HUD", type: "Distressed Asset Servicer" },
    { name: "LoanCare", category: "servicers", portal: "LoanCare Operations", sla: "< 24h", compliance: "100% GSE", type: "Subservicing Leader" },
    { name: "Rushmore Loan Management", category: "servicers", portal: "Rushmore REO Web", sla: "< 24h", compliance: "100% HUD", type: "Specialty Servicer" },
    { name: "Specialized Loan Servicing (SLS)", category: "servicers", portal: "SLS Vendor Portal", sla: "< 24h", compliance: "100% HUD", type: "Asset Servicing" },
    { name: "Valon Mortgage REO", category: "servicers", portal: "Valon API Link", sla: "< 24h", compliance: "100% GSE", type: "Tech-Enabled Servicer" },
    { name: "CrossCountry Mortgage REO", category: "servicers", portal: "CCM Field Hub", sla: "< 24h", compliance: "100% HUD", type: "National Lender" },
    { name: "Guaranteed Rate (Default)", category: "servicers", portal: "GR Field Operations", sla: "< 24h", compliance: "100% GSE", type: "Retail Lender" },
    { name: "Dovenmuehle Mortgage", category: "servicers", portal: "DMI Subservicing Gateway", sla: "< 24h", compliance: "100% GSE", type: "Subservicer" },
    { name: "First American Field Services", category: "servicers", portal: "First American Gateway", sla: "< 24h", compliance: "100% Title/GSE", type: "National Title & Field" },
    { name: "RES.NET", category: "servicers", portal: "RES.NET Real Estate Portal", sla: "< 12h", compliance: "100% Industry Standard", type: "REO SaaS Platform" },
    { name: "Equator", category: "servicers", portal: "Equator Asset Management", sla: "< 12h", compliance: "100% Industry Standard", type: "Default Workflow SaaS" },
    { name: "Aspen Grove Solutions", category: "servicers", portal: "iRecord / Aspen iAgency", sla: "< 12h", compliance: "100% Industry Standard", type: "Compliance Platform" },

    // --- 2. National Banks & Credit Unions ---
    { name: "J.P. Morgan Chase (REO Network)", category: "banks", portal: "Chase Default Gateway", sla: "< 24h", compliance: "100% Bank Grade", type: "Tier-1 Investment Bank" },
    { name: "US Bank REO Department", category: "banks", portal: "US Bank Field Link", sla: "< 24h", compliance: "100% Bank Grade", type: "National Bank" },
    { name: "Truist Bank REO", category: "banks", portal: "Truist Asset Operations", sla: "< 24h", compliance: "100% Bank Grade", type: "Regional Banking Leader" },
    { name: "CitiMortgage REO", category: "banks", portal: "Citi Asset Management", sla: "< 24h", compliance: "100% Bank Grade", type: "Global Banking Leader" },
    { name: "Fifth Third Bank REO", category: "banks", portal: "5/3 Field Gateway", sla: "< 24h", compliance: "100% Bank Grade", type: "Super-Regional Bank" },
    { name: "Huntington National Bank REO", category: "banks", portal: "Huntington Vendor Hub", sla: "< 24h", compliance: "100% Bank Grade", type: "Regional Bank" },
    { name: "Citizens Bank REO", category: "banks", portal: "Citizens Asset Hub", sla: "< 24h", compliance: "100% Bank Grade", type: "National Bank" },
    { name: "Regions Bank REO", category: "banks", portal: "Regions REO Link", sla: "< 24h", compliance: "100% Bank Grade", type: "Regional Bank" },
    { name: "KeyBank REO", category: "banks", portal: "KeyBank Field Solutions", sla: "< 24h", compliance: "100% Bank Grade", type: "Commercial & Retail Bank" },
    { name: "M&T Bank REO", category: "banks", portal: "M&T Asset Recovery", sla: "< 24h", compliance: "100% Bank Grade", type: "Commercial Bank" },
    { name: "First Horizon Bank REO", category: "banks", portal: "First Horizon Portal", sla: "< 24h", compliance: "100% Bank Grade", type: "Regional Bank" },
    { name: "Comerica Bank REO", category: "banks", portal: "Comerica Asset Hub", sla: "< 24h", compliance: "100% Bank Grade", type: "Financial Services Bank" },
    { name: "Zions Bank REO", category: "banks", portal: "Zions Asset Operations", sla: "< 24h", compliance: "100% Bank Grade", type: "Western Regional Bank" },
    { name: "Flagstar Bank REO", category: "banks", portal: "Flagstar Servicing Link", sla: "< 24h", compliance: "100% Bank Grade", type: "Mortgage Servicer" },
    { name: "Navy Federal Credit Union REO", category: "banks", portal: "NFCU Asset Management", sla: "< 24h", compliance: "100% Credit Union", type: "#1 US Credit Union" },
    { name: "State Employees Credit Union (SECU)", category: "banks", portal: "SECU Field Gateway", sla: "< 24h", compliance: "100% Credit Union", type: "Major Credit Union" },
    { name: "PenFed Credit Union REO", category: "banks", portal: "PenFed Asset Gateway", sla: "< 24h", compliance: "100% Credit Union", type: "National Credit Union" },
    { name: "BECU (Boeing Employees Credit Union)", category: "banks", portal: "BECU Asset Link", sla: "< 24h", compliance: "100% Credit Union", type: "Major Credit Union" },
    { name: "Golden 1 Credit Union REO", category: "banks", portal: "Golden 1 Field Link", sla: "< 24h", compliance: "100% Credit Union", type: "California Credit Union" },
    { name: "Suncoast Credit Union REO", category: "banks", portal: "Suncoast Portal", sla: "< 24h", compliance: "100% Credit Union", type: "Florida Credit Union" },
    { name: "Alliant Credit Union REO", category: "banks", portal: "Alliant Asset Bridge", sla: "< 24h", compliance: "100% Credit Union", type: "Digital Credit Union" },

    // --- 3. Institutional Single-Family Rental (SFR) & REO Operators ---
    { name: "Invitation Homes", category: "sfr", portal: "Invitation Homes Vendor Ops", sla: "< 24h", compliance: "Turnkey Turnaround", type: "#1 US SFR Operator" },
    { name: "Progress Residential", category: "sfr", portal: "Progress Property Portal", sla: "< 24h", compliance: "Institutional Standard", type: "Major SFR Portfolio" },
    { name: "American Homes 4 Rent (AMH)", category: "sfr", portal: "AMH Operations Hub", sla: "< 24h", compliance: "Turnkey Rehab", type: "Public SFR REIT" },
    { name: "FirstKey Homes", category: "sfr", portal: "FirstKey Vendor Link", sla: "< 24h", compliance: "Institutional Standard", type: "SFR Portfolio" },
    { name: "Tricon Residential", category: "sfr", portal: "Tricon Maintenance Web", sla: "< 24h", compliance: "Institutional Standard", type: "Blackstone SFR Platform" },
    { name: "Main Street Renewal", category: "sfr", portal: "MSR Vendor Gateway", sla: "< 24h", compliance: "Turnkey Rehab", type: "National SFR Operator" },
    { name: "Amherst (Renters Warehouse)", category: "sfr", portal: "Amherst Field Suite", sla: "< 24h", compliance: "Institutional Standard", type: "SFR Asset Manager" },
    { name: "Pathlight Property Management", category: "sfr", portal: "Pathlight Portal", sla: "< 24h", compliance: "Institutional Standard", type: "SFR Operator" },
    { name: "Sylvan Homes", category: "sfr", portal: "Sylvan Maintenance Hub", sla: "< 24h", compliance: "Institutional Standard", type: "SFR Portfolio" },
    { name: "Darwin Homes", category: "sfr", portal: "Darwin Field Ops", sla: "< 24h", compliance: "Institutional Standard", type: "Tech SFR Platform" },
    { name: "Mynd Property Management", category: "sfr", portal: "Mynd Vendor App", sla: "< 24h", compliance: "Institutional Standard", type: "Tech SFR Platform" },
    { name: "Auction.com", category: "sfr", portal: "Auction.com Vendor Network", sla: "< 12h", compliance: "100% REO Ready", type: "Top Real Estate Auction" },
    { name: "Hubzu", category: "sfr", portal: "Hubzu Asset Exchange", sla: "< 12h", compliance: "100% REO Ready", type: "Online Home Auction" },
    { name: "Williams & Williams", category: "sfr", portal: "W&W Real Estate Portal", sla: "< 24h", compliance: "100% REO Ready", type: "Auction House" },
    { name: "Offerpad", category: "sfr", portal: "Offerpad Renovation Hub", sla: "< 24h", compliance: "iBuyer Turnkey", type: "iBuyer Platform" },
    { name: "Opendoor", category: "sfr", portal: "Opendoor Vendor Gateway", sla: "< 24h", compliance: "iBuyer Turnkey", type: "National iBuyer" },
    { name: "Wedgewood Homes", category: "sfr", portal: "Wedgewood Rehab Portal", sla: "< 24h", compliance: "Turnkey Rehab", type: "Distressed Asset Buyer" },
    { name: "Greystar (SFR Division)", category: "sfr", portal: "Greystar Property Link", sla: "< 24h", compliance: "Class-A Institutional", type: "#1 US Property Manager" },
    { name: "Roofstock", category: "sfr", portal: "Roofstock Cloud Hub", sla: "< 24h", compliance: "Institutional Standard", type: "SFR Marketplace" },
    { name: "Pretium Partners", category: "sfr", portal: "Pretium Operations", sla: "< 24h", compliance: "Institutional Standard", type: "Investment Manager" },
    { name: "Blackstone Real Estate Portfolio", category: "sfr", portal: "BREP Institutional Link", sla: "< 24h", compliance: "Class-A Institutional", type: "Global Private Equity" },
    { name: "Starwood Capital Group REO", category: "sfr", portal: "Starwood Operations", sla: "< 24h", compliance: "Class-A Institutional", type: "Private Equity Leader" },

    // --- 4. Law Firms, Land Banks & Public Housing Authorities ---
    { name: "ALAW (Albertelli Law)", category: "legal_landbanks", portal: "ALAW Legal Network", sla: "< 24h", compliance: "100% Foreclosure Legal", type: "Default Legal Counsel" },
    { name: "McCalla Raymer Leibert Pierce", category: "legal_landbanks", portal: "MRLP Foreclosure Portal", sla: "< 24h", compliance: "100% Default Law", type: "National Default Firm" },
    { name: "Aldridge Pite", category: "legal_landbanks", portal: "Aldridge Pite Gateway", sla: "< 24h", compliance: "100% Default Law", type: "Multi-State Legal Firm" },
    { name: "Rubin Lublin", category: "legal_landbanks", portal: "Rubin Lublin Network", sla: "< 24h", compliance: "100% Default Law", type: "Default Servicing Law" },
    { name: "Trott Law", category: "legal_landbanks", portal: "Trott Law Case Bridge", sla: "< 24h", compliance: "100% Foreclosure Legal", type: "Midwest Default Counsel" },
    { name: "McCarthy Holthus", category: "legal_landbanks", portal: "MH Legal Operations", sla: "< 24h", compliance: "100% Default Law", type: "Western Default Counsel" },
    { name: "Padgett Law Group", category: "legal_landbanks", portal: "PLG Case System", sla: "< 24h", compliance: "100% Default Law", type: "Regional Default Firm" },
    { name: "New York City Housing Authority (NYCHA)", category: "legal_landbanks", portal: "NYCHA Facilities Portal", sla: "< 24h", compliance: "100% Public Housing", type: "#1 US Public Housing" },
    { name: "Housing Authority of City of LA (HACLA)", category: "legal_landbanks", portal: "HACLA Facility Gateway", sla: "< 24h", compliance: "100% Public Housing", type: "Major Housing Authority" },
    { name: "Chicago Housing Authority (CHA)", category: "legal_landbanks", portal: "CHA Operations Web", sla: "< 24h", compliance: "100% Public Housing", type: "Urban Housing Authority" },
    { name: "Detroit Land Bank Authority", category: "legal_landbanks", portal: "DLBA Preservation Hub", sla: "< 24h", compliance: "100% Municipal Blight", type: "#1 US Land Bank" },
    { name: "Cuyahoga Land Bank", category: "legal_landbanks", portal: "Cuyahoga Property System", sla: "< 24h", compliance: "100% Municipal Blight", type: "Ohio Land Bank" },
    { name: "Cook County Land Bank Authority", category: "legal_landbanks", portal: "Cook County Gateway", sla: "< 24h", compliance: "100% Municipal Blight", type: "Illinois Land Bank" },
    { name: "Philadelphia Land Bank", category: "legal_landbanks", portal: "Philly Land Operations", sla: "< 24h", compliance: "100% Municipal Blight", type: "Urban Land Bank" },
    { name: "US General Services Administration (GSA)", category: "legal_landbanks", portal: "GSA Real Property System", sla: "< 24h", compliance: "100% Federal Standard", type: "Federal Land Agency" },
    { name: "Texas Department of Transportation (TxDOT) ROW", category: "legal_landbanks", portal: "TxDOT ROW System", sla: "< 24h", compliance: "100% State Standard", type: "State Infrastructure" },

    // --- 5. Commercial REITs, Facilities & Disaster Networks ---
    { name: "CBRE (Property Services)", category: "commercial", portal: "CBRE Facility Gateway", sla: "< 24h", compliance: "Class-A Commercial", type: "Global Real Estate Leader" },
    { name: "JLL (Field Services)", category: "commercial", portal: "JLL Operations Suite", sla: "< 24h", compliance: "Class-A Commercial", type: "Global Real Estate Services" },
    { name: "Cushman & Wakefield (Field)", category: "commercial", portal: "C&W Facility Link", sla: "< 24h", compliance: "Class-A Commercial", type: "Commercial Asset Leader" },
    { name: "Colliers International (Special Assets)", category: "commercial", portal: "Colliers Bridge", sla: "< 24h", compliance: "Institutional Standard", type: "Commercial Real Estate" },
    { name: "Belfor Property Restoration", category: "commercial", portal: "Belfor Disaster Network", sla: "< 12h", compliance: "Disaster Standard", type: "#1 Global Restoration" },
    { name: "Servpro National Accounts", category: "commercial", portal: "Servpro Corporate Link", sla: "< 12h", compliance: "Disaster Standard", type: "National Restoration" },
    { name: "Paul Davis Restoration", category: "commercial", portal: "Paul Davis Field Ops", sla: "< 12h", compliance: "Disaster Standard", type: "Restoration Network" },
    { name: "Public Storage", category: "commercial", portal: "Public Storage Facilities", sla: "< 24h", compliance: "Commercial Standard", type: "#1 Self Storage REIT" },
    { name: "Extra Space Storage", category: "commercial", portal: "Extra Space Gateway", sla: "< 24h", compliance: "Commercial Standard", type: "Storage REIT" },
    { name: "American Tower Corporation", category: "commercial", portal: "ATC Infrastructure Web", sla: "< 24h", compliance: "Telecom Standard", type: "Global Tower REIT" },
    { name: "Crown Castle", category: "commercial", portal: "Crown Castle Asset Link", sla: "< 24h", compliance: "Telecom Standard", type: "Communications REIT" },
    { name: "AshBritt Environmental", category: "commercial", portal: "AshBritt Disaster System", sla: "< 12h", compliance: "FEMA Certified", type: "Disaster Recovery" },
    { name: "Tetra Tech (Emergency Management)", category: "commercial", portal: "Tetra Tech Dispatch", sla: "< 12h", compliance: "FEMA Certified", type: "Disaster Engineering" }
];
